<?php

/********************************************************* {COPYRIGHT-TOP} ***
 * Licensed Materials - Property of IBM
 * 5725-L30, 5725-Z22
 *
 * (C) Copyright IBM Corporation 2018, 2025
 *
 * All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 ********************************************************** {COPYRIGHT-END} **/

/**
 * @file
 * Provides user management integration with APIC.
 */

use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_menu().
 *
 * @param $variables
 */
function auth_apic_preprocess_menu(&$variables) {
  if (isset($variables['menu_name']) && $variables['menu_name'] === 'account' && array_key_exists('change_pwd_page.change_password', $variables['items'])) {
    $currentUser = \Drupal::currentUser();
    if (!$currentUser->isAnonymous() && $currentUser->id() !== 1) {
      $currentUser = User::load($currentUser->id());
      $registryUrl = $currentUser->get('registry_url')->value;
      if ($registryUrl !== NULL && $registryUrl !== '/admin') {
        $registry = \Drupal::service('ibm_apim.user_registry')->get($registryUrl);
        if ($registry !== NULL) {
          $ro = !$registry->isUserManaged();
          if ($ro === TRUE) {
            unset($variables['items']['change_pwd_page.change_password']);
          }
        }
      }
    }
  }
}

/**
 * Need to use our custom content forms for users
 *
 * @param $variables
 * @param $hook
 * @param $info
 */
function auth_apic_preprocess(&$variables, $hook, &$info) {

  if ($hook === 'form') {

    if ($variables['element']['#form_id'] === 'user_login_form' || $variables['element']['#form_id'] === 'user_register_form') {
      $templateFileName = 'form--' . str_replace('_', '-', $variables['element']['#form_id']);
    }
    elseif ($variables['element']['#form_id'] === 'user_pass' || $variables['element']['#form_id'] === 'apic_resetpw' || $variables['element']['#form_id'] === 'user_pass_reset') {
      $templateFileName = 'form--user-pass-form';
    }
    elseif ($variables['element']['#form_id'] === 'apic_change_pwd_form') {
      $templateFileName = 'form--change-pwd-form';
    }

    if (isset($templateFileName)) {
      if (function_exists('ibm_apim_entry_trace')) {
        ibm_apim_entry_trace(__FUNCTION__, 'form');
      }
      $theme_name = \Drupal::theme()->getActiveTheme()->getName();
      $theme_path = \Drupal::theme()->getActiveTheme()->getPath();
      if (file_exists($theme_path . '/templates/form/' . $templateFileName . '.html.twig')) {
        $info['theme path'] = \Drupal::service('extension.list.theme')->getPath($theme_name);
        $info['path'] = \Drupal::service('extension.list.theme')->getPath($theme_name) . '/templates/form';
        $info['template'] = $templateFileName;
      }
      elseif (file_exists($theme_path . '/templates/' . $templateFileName . '.html.twig')) {
        $info['theme path'] = \Drupal::service('extension.list.theme')->getPath($theme_name);
        $info['path'] = \Drupal::service('extension.list.theme')->getPath($theme_name) . '/templates';
        $info['template'] = $templateFileName;
      }
      else {
        $templateFilePath = \Drupal::service('extension.list.module')->getPath('auth_apic') . '/templates/' . $templateFileName . '.html.twig';
        if (file_exists($templateFilePath)) {
          $info['theme path'] = \Drupal::service('extension.list.module')->getPath('auth_apic');
          $info['path'] = \Drupal::service('extension.list.module')->getPath('auth_apic') . '/templates';
          $info['template'] = $templateFileName;
        }
      }
      if (function_exists('ibm_apim_entry_trace')) {
        ibm_apim_exit_trace(__FUNCTION__, 'form');
      }
    }
  }
}
