field.field.node.api.api_ibmconfiguration:
  type: ibm_apim_config_object
  label: 'IBM Configuration'

field.field.node.api.api_id:
  type: ibm_apim_config_object
  label: 'ID'

field.field.node.api.api_oaiversion:
  type: ibm_apim_config_object
  label: 'OAI Version'

field.field.node.api.api_protocol:
  type: ibm_apim_config_object
  label: 'Protocol'

field.field.node.api.api_soapversion:
  type: ibm_apim_config_object
  label: 'SOAP Version'

field.field.node.api.api_state:
  type: ibm_apim_config_object
  label: 'State'

field.field.node.api.api_swagger:
  type: ibm_apim_config_object
  label: 'Open API Document'

field.field.node.api.api_encodedswagger:
  type: ibm_apim_config_object
  label: 'Encoded Open API Document'

field.field.node.api.api_swaggertags:
  type: ibm_apim_config_object
  label: 'Open API Tags'

field.field.node.api.api_wsdl:
  type: ibm_apim_config_object
  label: 'WSDL Content'

field.field.node.api.api_xibmname:
  type: ibm_apim_config_object
  label: 'X-IBM-Name'

field.field.node.api.apic_attachments:
  type: ibm_apim_config_object
  label: 'Documentation'

field.field.node.api.apic_catalog_id:
  type: ibm_apim_config_object
  label: 'APIC Catalog ID'

field.field.node.api.apic_description:
  type: ibm_apim_config_object
  label: 'Description'

field.field.node.api.apic_hostname:
  type: ibm_apim_config_object
  label: 'APIC Hostname'

field.field.node.api.apic_image:
  type: ibm_apim_config_object
  label: 'Image'

field.field.node.api.apic_pathalias:
  type: ibm_apim_config_object
  label: 'Path Alias'

field.field.node.api.apic_provider_id:
  type: ibm_apim_config_object
  label: 'APIC Provider ID'

field.field.node.api.apic_rating:
  type: ibm_apim_config_object
  label: 'Rating'

field.field.node.api.apic_ref:
  type: ibm_apim_config_object
  label: 'Reference'

field.field.node.api.apic_summary:
  type: ibm_apim_config_object
  label: 'Summary'

field.field.node.api.apic_tags:
  type: ibm_apim_config_object
  label: 'Tags'

field.field.node.api.apic_url:
  type: ibm_apim_config_object
  label: 'URL'

field.field.node.api.apic_version:
  type: ibm_apim_config_object
  label: 'Version'

field.field.node.api.apic_created_at:
  type: ibm_apim_config_object
  label: 'Creation time'

field.field.node.api.apic_updated_at:
  type: ibm_apim_config_object
  label: 'Modification time'

field.field.node.api.comment:
  type: ibm_apim_config_object
  label: 'Comments'

views.view.apis.display.default.display_options.exposed_form.options:
  type: string
  sort_asc_label: 'Asc'

views.view.apis.display.default.display_options.exposed_form.options:
  type: string
  sort_desc_label: 'Desc'

views.view.apis.display.default.display_options.exposed_form.options:
  type: string
  exposed_sorts_label: 'Sort by'

views.view.apis.display.default.display_options.exposed_form.options:
  type: string
  reset_button_label: 'Reset'

views.view.apis.display.default.display_options.exposed_form.options:
  type: string
  submit_button: 'Apply'

views.view.apis.display.default.display_options.exposed_form.options:
  type: string
  text_input_required: 'Select any filter and click on Apply to see results'

views.view.apis.display.default.display_options.exposed_form.options.bef.sort.advanced:
  type: string
  collapsible_label: 'Sort options'

views.view.apis.display.default.display_options.exposed_form.options.bef.general:
  type: string
  secondary_label: 'Advanced options'

views.view.apis.display.default.display_options.filters.title.expose:
  type: string
  label: 'Name'

views.view.apis.display.default.display_options.filters.term_node_tid_depth.expose:
  type: string
  label: 'Category'

views.view.apis.display.default.display_options.sorts.title.expose:
  type: string
  label: 'Name'

views.view.apis.display.default.display_options.sorts.apic_version_value.expose:
  type: string
  label: 'Version'

views.view.apis.display.default.display_options.sorts.apic_rating_status.expose:
  type: string
  label: 'Rating'

views.view.apis.display.default.display_options.sorts.created.expose:
  type: string
  label: 'Created'

views.view.apis.display.default.display_options.sorts.changed.expose:
  type: string
  label: 'Changed'

views.view.apis.display.default.display_options:
  type: string
  title: 'APIs'

views.view.apis.display.block_1.display_options:
  type: string
  title: 'API List'

views.view.apis.display.block_1.display_options.sorts.title.expose:
  type: string
  label: 'Name'

views.view.apis.display.page_1.display:
  type: string
  title: 'Page'

views.view.product_content:
  type: string
  label: 'Product Content'

views.view.product_content.display.default.display_options.pager.options.expose:
  type: string
  items_per_page_label: 'APIs per page'

views.view.product_content.display.default.display_options:
  type: string
  title: 'Product Content'

views.view.product_content.display.page_1.display:
  type: string
  title: 'Page'