#!groovy

// Load shared pipeline library
@Library('velox') _

// Clean up builds older than 30 days
properties([
  durabilityHint('PERFORMANCE_OPTIMIZED'),
  buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '14', numToKeepStr: '')),
])

def pipelineOpts = [
  slackChannel: '',
  labels: 'portal-taas',
  nodeVersion: null,
]

veloxPipeline(pipelineOpts) { p ->

  def MODULE_NAME = 'apictest'

  p.branch(~/master|\d+\.\d+|\d+\.\d+\.\d+/) {

    stage('Upload module to artifactory') {
      portal.uploadComposerPackage("${MODULE_NAME}")
    }

  }

}
