<?php
/********************************************************* {COPYRIGHT-TOP} ***
 * Licensed Materials - Property of IBM
 * 5725-L30, 5725-Z22
 *
 * (C) Copyright IBM Corporation 2015, 2020
 *
 * All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 ********************************************************** {COPYRIGHT-END} **/

/**
 * IBM API Connect Integration
 *
 * Adds the Plan node content type to Drupal for representing Plans from IBM APIC
 */

/**
 * Implements hook_node_info().
 */
function plan_node_info() {
  return array(
    'plan' => array(
      'name' => t('Plan'),
      'base' => 'plan',
      'description' => t('A Plan in IBM API Connect')
    )
  );
}

/**
 * Implements hook_help().
 */
function plan_help($path, $arg) {
  switch ($path) {
    case 'admin/help#plan' :
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("The plan module provides a new custom node type for use with IBM API Connect.") . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Select a plan') . '</dt>';
      $output .= '<dd>' . t("This module enables the user to see the different plans available in IBM API Connect for a given API, showing the details and any rate limiting policy included in them.") . '</dd>';
      $output .= '<dt>' . t('Subscribe to a plan') . '</dt>';
      $output .= '<dd>' . t("Using this module it is possible for a user to subscribe an application to a plan in IBM API Connect.") . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_form().
 */
function plan_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_view().
 */
function plan_view($node, $view_mode) {
  return $node;
}

/**
 * Implements hook_node_view().
 */
function plan_node_view($node, $view_mode) {
}
