<?php

/********************************************************* {COPYRIGHT-TOP} ***
 * Licensed Materials - Property of IBM
 * 5725-L30, 5725-Z22
 *
 * (C) Copyright IBM Corporation 2018
 *
 * All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 ********************************************************** {COPYRIGHT-END} **/

/**
 * @file
 * Provides a Social block.
 */

use Abraham\TwitterOAuth\TwitterOAuth;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\encrypt\Entity\EncryptionProfile;

/**
 * Add twig template
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function socialblock_theme($existing, $type, $theme, $path) {
  return array(
    'socialblock_block' => array(
      'variables' => array(
        'posts' => NULL
      )
    )
  );
}

/**
 * @return array
 */
function socialblock_get_forum_vocabularies() {

  $vocabs = array();

  $systemvocabs = Vocabulary::loadMultiple();

  if (isset($systemvocabs)) {
    foreach ($systemvocabs as $vocab) {
      if ($vocab->label() == 'Forums') {
        $vocabs = \Drupal::getContainer()
          ->get('entity.manager')
          ->getStorage('taxonomy_term')
          ->loadTree($vocab->id());
      }
    }
  }

  return $vocabs;
}

/**
 * @return array
 */
function socialblock_get_forum_term_ids() {

  $vocabs = socialblock_get_forum_vocabularies();

  $tids = array();
  if (isset($vocabs)) {
    foreach ($vocabs as $vocab) {
      $tids[$vocab->tid] = intval($vocab->tid);
    }
  }

  return $tids;
}

/**
 * @param DateInterval $di
 * @return string
 */
function socialblock_get_timediff(DateInterval $di) {

  $translate = \Drupal::translation();

  $years = $di->y;
  $months = $di->m;
  $days = $di->d;
  $hours = $di->h;
  $minutes = $di->i;
  $seconds = $di->s;

  $secondsString = \Drupal::translation()
    ->formatPlural($seconds, '1 second ago', '@count seconds ago');
  $minutesString = \Drupal::translation()
    ->formatPlural($minutes, '1 minute ago', '@count minutes ago');
  $hoursString = \Drupal::translation()
    ->formatPlural($hours, '1 hour ago', '@count hours ago');
  $daysString = \Drupal::translation()
    ->formatPlural($days, '1 day ago', '@count days ago');
  $monthsString = \Drupal::translation()
    ->formatPlural($months, '1 month ago', '@count months ago');
  $yearsString = \Drupal::translation()
    ->formatPlural($minutes, '1 year ago', '@count years ago');

  $diff = $years == 0 ? ($months == 0 ? ($days == 0 ? ($hours == 0 ? ($minutes == 0 ? ($seconds == 0 ? t('Just now') : $secondsString) : $minutesString) : $hoursString) : $daysString) : $monthsString) : $yearsString;

  return $diff;
}

/**
 * @param DateInterval $di
 * @return null|string
 */
function socialblock_get_tweet_timediff(DateInterval $di) {

  $years = $di->y;
  $months = $di->m;
  $days = $di->d;
  $hours = $di->h;
  $minutes = $di->i;
  $seconds = $di->s;
  $diff = $years == 0 ? ($months == 0 ? ($days == 0 ? ($hours == 0 ? ($minutes == 0 ? ($seconds == 0 ? t('now') : $seconds . t('s')) : $minutes . t('m')) : $hours . t('h')) : $days . t('d')) : $months . t('M')) : $years . t('y');

  return $diff;
}

/**
 * Implements hook_cron().
 */
function socialblock_cron() {

  $config_instances = \Drupal::state()->get('socialblock.config');
  if (isset($config_instances) && !empty($config_instances)) {
    foreach ($config_instances as $block_uuid => $settings) {

      $numberOfTiles = $settings['numberOfTiles'];
      $forumsList = $settings['forumsList'];                // In the form of array(forumId => [0|1])
      $twitterSearchBy = $settings['twitterSearchBy'];      // In the form of 0 = userid, 1 = search;
      $twitterSearchParameter = $settings['twitterSearchParameter'];
      $twitterTweetTypes = $settings['twitterTweetTypes'];  // In the form of 0 = tweets, 1 = tweets and replies

      // These are the settings for the twitter oauth
      $config = \Drupal::config('socialblock.settings');
      $data = $config->get('credentials');
      if (isset($data) && !empty($data)) {
        $encryption_profile = EncryptionProfile::load('socialblock');
        if (isset($encryption_profile)) {
          $settings = unserialize(\Drupal::service('encryption')->decrypt($data, $encryption_profile));
        }
        else {
          \Drupal::logger('socialblock')->info('Social Block : The "socialblock" encryption profile is missing.');
          $settings = array();
        }
      }
      else {
        $settings = array();
      }
      if (!isset($settings['consumerKey'])) {
        $settings['consumerKey'] = '';
      }
      if (!isset($settings['consumerSecret'])) {
        $settings['consumerSecret'] = '';
      }
      if (!isset($settings['accessToken'])) {
        $settings['accessToken'] = '';
      }
      if (!isset($settings['accessTokenSecret'])) {
        $settings['accessTokenSecret'] = '';
      }

      if (isset($settings['consumerKey']) && !empty($settings['consumerKey']) && isset($settings['consumerSecret']) && !empty($settings['consumerSecret']) && isset($settings['accessToken']) && !empty($settings['accessToken']) && isset($settings['accessTokenSecret']) && !empty($settings['accessTokenSecret'])) {
        $api = "";
        $api_param = "";

        switch ($twitterSearchBy) {

          // Show tweets for a given user id
          case 0;
            $api = 'statuses/user_timeline';
            $api_param = 'screen_name';
            break;

          // Show tweets mactching a search term
          case 1;
            $api = 'search/tweets';
            $api_param = 'q';
            break;
        }

        $tweets = array();

        switch ($twitterTweetTypes) {

          // Displaying just tweets
          case 0:
            $remaining_calls = socialblock_not_rate_limited($settings);

            if ($remaining_calls > 0) {
              $temp = socialblock_call_twitter_api($settings, $api, array(
                $api_param => $twitterSearchParameter,
                'count' => $numberOfTiles
              ));
              $temp2 = $temp;
              $remaining_calls--;
              $all_tweets = FALSE;

              while (!$all_tweets) {
                if ($remaining_calls > 0 && !empty($temp)) {
                  $max_id = end($temp)->id;
                  for ($i = 0; $i < sizeof($temp); $i++) {
                    if (is_null($temp[$i]->in_reply_to_status_id)) {
                      array_push($tweets, $temp[$i]);
                    }
                  }
                  $all_tweets = sizeof($tweets) == $numberOfTiles;
                  if (!$all_tweets) {
                    $temp = socialblock_call_twitter_api($settings, $api, array(
                      $api_param => $twitterSearchParameter,
                      'count' => $numberOfTiles - sizeof($tweets),
                      'max_id' => $max_id - 1
                    ));
                    $remaining_calls--;
                    $temp2 = empty($temp) ? $temp2 : $temp;
                  }
                }
                else {
                  $tweets = $temp2;
                  $all_tweets = TRUE;
                }
              }
            }
            else {
              \Drupal::logger('socialblock')
                ->info('Social Block : Twitter API rate limit hit!');
            }
            break;

          // Tweets and replies
          case 1:
            $remaining_calls = socialblock_not_rate_limited($settings);
            if ($remaining_calls > 0) {
              $tweets = socialblock_call_twitter_api($settings, $api, array(
                $api_param => $twitterSearchParameter,
                'count' => $numberOfTiles
              ));
            }
            else {
              \Drupal::logger('socialblock')
                ->info('Social Block : Twitter API rate limit hit!');
            }
            break;
          default:
            $tweets = array();
        }

        // Store tweets as state config so that we can use it when rendering the socialblock
        $data_instances = \Drupal::state()->get('socialblock.data');
        if (!isset($data_instances)) {
          $data_instances = array();
        }
        $data_instances[$block_uuid] = $tweets;

        \Drupal::state()->set('socialblock.data', $data_instances);

        \Drupal::logger('socialblock')
          ->info('Social Block : Retrieved %num_tweets tweets for block with uuid [%uuid]', array(
            "%num_tweets" => sizeof($tweets),
            "%uuid" => $block_uuid
          ));

      } // we had complete twitter credentials

    } // foreach($blocks as $blockid)
  }
}


/**
 * @param $credentials
 * @param $api
 * @param $params
 * @return array|null|object
 */
function socialblock_call_twitter_api($credentials, $api, $params) {

  $consumerKey = $credentials['consumerKey'];
  $consumerSecret = $credentials['consumerSecret'];
  $accessToken = $credentials['accessToken'];
  $accessTokenSecret = $credentials['accessTokenSecret'];

  $connection = new TwitterOAuth($consumerKey, $consumerSecret, $accessToken, $accessTokenSecret);
  $connection->host = "https://api.twitter.com/1.1";
  $response = $connection->get($api, $params);

  if (isset($response->errors)) {
    $response = NULL;
  }
  else {
    if ($api == 'search/tweets') {
      $response = $response->statuses;
    }
  }

  return $response;
}

/**
 * @param $cred
 * @return bool
 */
function socialblock_not_rate_limited($cred) {
  $result = socialblock_call_twitter_api($cred, 'application/rate_limit_status', array('resources' => 'statuses'));
  if (isset($result->resources->statuses->{'/statuses/user_timeline'}->remaining) && $result->resources->statuses->{'/statuses/user_timeline'}->remaining > 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * @param $a
 * @param $b
 * @return int
 */
function socialblock_sort_by_created($a, $b) {
  $at = intval($a->tweet ? strtotime($a->created_at) : $a->created->getValue()[0]['value']);
  $bt = intval($b->tweet ? strtotime($b->created_at) : $b->created->getValue()[0]['value']);
  if ($at == $bt) {
    return 0;
  }
  return $at < $bt ? 1 : -1;
}

function socialblock_expand_url($url) {
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_HEADER, TRUE);
  curl_setopt($ch, CURLOPT_NOBODY, 1);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, FALSE);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
  curl_setopt($ch, CURLOPT_TIMEOUT, 10);
  $a = curl_exec($ch);
  curl_close($ch);
  if (preg_match('#Location: (.*)#', $a, $r)) {
    $l = trim($r[1]);
    return $l;
  }
  else {
    return $url;
  }
}
