<?php

/**
 * @file
 * Provides a Github Markdown input filter.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return mixed
 */
function ghmarkdown_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.ghmarkdown') {
    return t('<p>The Markdown filter allows you to enter content using <a href="https://guides.github.com/features/mastering-markdown/">Github Markdown</a>, a simple plain-text syntax that is transformed into valid HTML.</p>');
  }
}



