<?php
/********************************************************* {COPYRIGHT-TOP} ***
 * Licensed Materials - Property of IBM
 * 5725-L30, 5725-Z22
 *
 * (C) Copyright IBM Corporation 2015, 2021
 *
 * All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 ********************************************************** {COPYRIGHT-END} **/

/**
 * * Implements hook_bean_types_api_info().
 */
function popularproduct_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Utility method to truncate a string at a specified length and append an ellipsis
 * @param $string
 * @param int $length
 * @param string $append
 * @return array|string
 */
function popularproduct_truncate_string($string, $length = 250, $append = "…") {
  $string = trim($string);
  if (strlen($string) > $length) {
    $string = wordwrap($string, $length);
    $string = explode("\n", $string, 2);
    $string = trim($string[0]) . $append;
  }
  return $string;
}

/**
 * * Implements hook_bean_types().
 */
function popularproduct_bean_types() {
  $plugins = array();
  $plugins['popularproduct_block'] = array(
    'label' => t('Popular Product'),
    'description' => t('A featured Product block.'),
    'handler' => array(
      'class' => 'PopularProductBlockBean',
      'parent' => 'bean',
      'path' => drupal_get_path('module', 'popularproduct') . '/plugins/bean',
      'file' => 'popularproduct.popularproduct_block.inc',
    ),
  );
  return $plugins;
}

/**
 * Implementation of hook_form_alter()
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function popularproduct_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'bean_form' :
      $bean = $form['bean']['#value'];
      if (isset($bean) && isset($bean->type) && $bean->type == 'popularproduct_block') {
        if (isset($form['title'])) {
          unset($form['title']);
        }
        if ($form['view_mode']) {
          unset($form['view_mode']);
          $form['view_mode'] = array('#type' => 'hidden', '#value' => 'default');
        }
      }
      break;
  }
}
