restrict_by_ip.settings:
  type: config_object
  mapping:
    header:
      type: string
      label: Server header to check for user IP address
    error_page:
      type: string
      label: Page user is redirected to when login is denied
    login_range:
      type: string
      label: Global IP address login restrictions
    user:
      type: sequence
      label: User level IP address login restrictions
      sequence:
        type: string
    role:
      type: sequence
      label: Role level IP address grant restrictions
      sequence:
        type: string
    dependencies:
      type: config_dependencies
      label: Dependencies
