name: Product
type: module
description: Products from IBM API Developer Portal
package: IBM API Developer Portal
core_version_requirement: ^8 || ^9
version: 8.x-2.14.1
project: product
dependencies:
- path
- file
- image
- consumerorg:consumerorg
- ibm_apim:ibm_apim
- apic_app:apic_app
- node
- user
- votingapi_widgets
- select_translation
- cshs
- comment
- taxonomy
- views
- masonry
- masonry_views
- better_exposed_filters
- views_autocomplete_filters
- twig_tweak
- smart_trim
interface translation project: product
